### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by neugartf** [primaryobjects/lda#5]
I'd love to have support for multiple languages for the stop words. I can provide some lists, but I just wanted to ask how this should be implemented. Maybe an initialiser where you can define your language? We probably don't want to run against a whole list of stop words containing words in every languages.

**Comment by primaryobjects** [comment]
Maybe modifying the main lda() [parameters](https://github.com/primaryobjects/lda/blob/master/lib/lda.js#L8), to accept an optional string for language.

``` javascript
var process = function(sentences, numberOfTopics, numberOfTermsPerTopic, language, alphaValue, betaValue) {
   language = language || 'english';

   ...
}
```

Next, there would need to be a way to overwrite the stop_words array with the values in the other language file (stopwords-spanish.js, stopwords-german.js, etc). I'm not sure if you can do a conditional 'require', so maybe somehow overwrite the default array in the conditional.

Feel free to create a fork. Thanks.

**Comment by primaryobjects** [comment]
I've merged your changes, updated the version, and updated the [Readme](https://github.com/primaryobjects/lda/blob/master/Readme.md#additional-languages) to document the new language support.

If you have any other languages that you wanted to add let me know, otherwise I'll publish the update to npm.

Thanks again.

**Comment by neugartf** [comment]
Thank you for the fast merge and the added documentation
